baseurl: /philgough
title: Phil Gough's Personal Blog
subtitle: Phil Gough's blog
remote-theme: clayh53/tufte-jekyll
author: Phil Gough
simple_search: http://google.com/search
description: Based on the Jekyll theme for content-rich sites
name: Phil Gough
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
# permalink: /:categories/:title/
timezone: Australia/Sydney
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/git/philgough.github.io/
plugins:
  - jekyll-target-blank


  